### ISSUE TITLE
Remove thumbprint

### ISSUE THREAD

**Issue by pas256** [terraform-module/terraform-aws-github-oidc-provider#84]
### Description of Problem:
The IAM page is recommending against using thumbprints going forward. See screenshot:

![Screenshot 2024-05-14 at 2 01 43 PM](https://github.com/terraform-module/terraform-aws-github-oidc-provider/assets/92010/4a3d3d88-5600-45c4-ac3e-c5d1b6b15dbe)

### Potential Solutions:
Remove the thumbprint variable and associated references

**Comment by fideloper** [comment]
Terraform requires that field tho currently.
